code_label = "cp2k@localhost"

[metadata_options]
num_machines = 2
num_mpiprocs_per_machine = 128
max_wallclock_seconds = 86400
memory_per_machine_mb = 614400
partition = "cpu-genoa"

[cp2k]
cutoff = 400
kpoints_distance = 0.3

[gw]
kpoints_distance = 0.06
kpoints_w_distance = 0.06
cutoff = 400
rel_cutoff = 50
periodic = "XZ"
num_time_freq = 10
memory_per_proc = 600
eps_filter = 1.0e-6
cutoff_radius_ri = 5
regularization_ri = 0.01
eps_default = 1.0e-12
eps_pgf_orb = 1.0e-12
eps_scf = 5.0e-7
max_scf = 500
mixing_alpha = 0.2
mixing_beta = 0.8
mixing_nbroyden = 10
vacuum = 20.0
supercell = [2, 2, 1]
bs_npoints = 20
orb_basis = "aug-SZV-MOLOPT-GTH-tier-1"
basis_set_file = "/home/tahmas41/work/GW_2D/BASIS_AUG_MOLOPT/BASIS_GTH_MOLOPT_AUG_for_excited_states"
ri_basis_set_file = "/home/tahmas41/work/GW_2D/BASIS_AUG_MOLOPT/BASIS_GTH_MOLOPT_AUG_for_excited_states_RI"
potential_file = "/home/tahmas41/work/GW_2D/cp2k/data/POTENTIAL_UZH"
resolve_from_files = true
ri_basis_accuracy_target = 1e-6
