MP_api:
  api_key:
aiida_settings:
  DFT_code_string: CP2K2025@otusn # cp2k@noctua2n
job_script:
  geopt:
    number_of_jobs: 10
    nodes: 1
    ntasks: 48
    ncpu: 1
    time: 28800 #in s
    exclusive: False

