MP_api:
  api_key: 
aiida_settings:
  DFT_code_string:
  FLAME_code_string:
job_script:
  geopt:
    number_of_jobs: 40
    nodes:
    ntasks:
    ncpu:
    time: #in s
    exclusive: False
  gensymcrys:
    number_of_jobs: 5
    nodes:
    ntasks:
    time: #in s
    exclusive: False
